import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../lib/api';
import { FileText, Loader2 } from 'lucide-react';

export function ReportsListPage() {
  const nav = useNavigate();
  const [reports, setReports] = useState<Record<string, unknown>[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.getReports().then(r => setReports(r)).catch(console.error).finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="flex items-center justify-center min-h-[60vh]"><Loader2 className="animate-spin text-[#0F6E56]" size={32} /></div>;

  return (
    <div className="max-w-3xl mx-auto px-4 py-6">
      <h1 className="text-xl font-bold text-gray-900 mb-6">Reports</h1>

      {reports.length === 0 ? (
        <div className="text-center py-16 text-gray-400">
          <FileText size={40} className="mx-auto mb-3 opacity-40" />
          <p className="text-sm">No reports generated yet.</p>
          <p className="text-xs mt-1">Review all incidents in the dashboard to generate a report.</p>
        </div>
      ) : (
        <div className="space-y-2">
          {reports.map((r: any) => (
            <button key={r.id} onClick={() => nav(`/reports/${r.id}`)}
              className="w-full bg-white rounded-xl border border-gray-200 p-4 flex items-center gap-4 text-left hover:bg-gray-50 transition-colors">
              <div className="w-10 h-10 rounded-lg bg-[#E1F5EE] flex items-center justify-center flex-shrink-0">
                <FileText size={20} className="text-[#0F6E56]" />
              </div>
              <div className="flex-1">
                <p className="text-sm font-semibold text-gray-900">
                  {new Date(r.period_start).toLocaleDateString('en-NZ', { day: 'numeric', month: 'short', year: 'numeric' })} — {new Date(r.period_end).toLocaleDateString('en-NZ', { day: 'numeric', month: 'short', year: 'numeric' })}
                </p>
                <p className="text-xs text-gray-500">Generated by {r.generated_by} on {new Date(r.generated_at).toLocaleDateString('en-NZ', { day: 'numeric', month: 'short' })}</p>
              </div>
              {r.locked && <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-green-100 text-green-700">Locked</span>}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
